CREATE TABLE spectral_reading (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id         VARCHAR(255)            NOT NULL,
    timestamp         TIMESTAMP WITH TIME ZONE NOT NULL,
    peak_wavelength   DOUBLE PRECISION        NOT NULL,
    intensities       TEXT                    NOT NULL,
    refractive_index  DOUBLE PRECISION        NOT NULL,
    delta_n           DOUBLE PRECISION        NOT NULL,
    risk_score        DOUBLE PRECISION        NOT NULL
);
