CREATE TABLE alert (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id         VARCHAR(255)            NOT NULL,
    timestamp         TIMESTAMP WITH TIME ZONE NOT NULL,
    alert_type        VARCHAR(255)            NOT NULL,
    severity          VARCHAR(255)            NOT NULL,
    alert_message     TEXT                    NOT NULL,
    acknowledged      BOOLEAN                 NOT NULL DEFAULT FALSE
);
